// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adikwbhwdpaiiecgswlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkaWt3Ymh3ZHBhaWllY2dzd2xjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MjAzNDIsImV4cCI6MjA1NzI5NjM0Mn0.mDimwUn7Osv3KUn75szFHws4-haPFNakWv6F1AP3uZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);